/*
	Program: bankAccount.cpp
	Author: Anthony Rolfe
	Organization: Grantham University
	Date: 7/11/2019

	Description: This file implements the bankAccount class created and defined in bankAccount.h
*/


#include "bankAccount.h"
#include <string>
#include <iostream>
#include <iomanip>

int bankAccount::nextAccountNumber = 1900000001;

bankAccount::bankAccount()
{
	accountHolderName = "";
	accountType = "Checking";
	balance = 0.0;
	interestRate = 0.0;
	nextAccountNumber++;
}

bankAccount::bankAccount(std::string name, std::string type, double openingBalance, double rate)
	// Constructor using supplied data.
{
	accountHolderName = name;
	accountType = type;
	accountNumber = nextAccountNumber;
	balance = openingBalance;
	interestRate = rate;
	nextAccountNumber ++;	
}

void bankAccount::deposit(double amount)
	//Function to add a deposit to the balance. Effectively ignores non-positive amounts.
{
	if (amount > 0)
	{
		balance += amount;
	}
	else
	{
		balance += 0;
	}
}

void bankAccount::withdraw(double amount)
	//Function to subtract a withdrawl from the balance. Effectively ignores non-positive amounts.
{
	if (amount > 0)
	{
		balance -= amount;
	}
	else
	{
		balance -= 0;
	}
}

double bankAccount::getInterest()
	//Function to obtain the interest generated by the account balance.
{
	return balance * interestRate;
}

void bankAccount::updateBalance()
	//Function to update the account balance with the interest that was generated.
{
	double interestGenerated = getInterest();
	balance += interestGenerated;
}

void bankAccount::print() const
	//Function to print the account data.
{
	std::cout << "********************" << accountType << " Account " << accountNumber 
		<< "********************" << std::endl;	
	std::cout << "ACCOUNT HOLDER'S NAME: " << accountHolderName << std::endl;
	std::cout << std::fixed << std::setprecision(2) << std::showpoint << "BALANCE: $" << balance << std::endl;
	std::cout << "INTEREST RATE: " << interestRate * 100 << "%" << std::endl;
	std::cout << "*******************************************************************" << std::endl;
}

int bankAccount::getAccountNumber()
	//Function to obtain account number.
{
	return accountNumber;
}

std::string bankAccount::getAccountHolderName()
	//Function to obtain the Account Holder's name.
{
	return accountHolderName;
}

std::string bankAccount::getAccountType()
	//Function to obtain the Account Type.
{
	return accountType;
}

double bankAccount::getBalance()
	//Function to obtain the current account balance.
{
	return balance;
}

double bankAccount::getInterestRate()
	//Function to obtain the current account interest rate.
{
	return interestRate;
}
